"""empty message

Revision ID: 0a77f1b2e054
Revises: 586402ca7cbc
Create Date: 2020-02-01 11:06:34.168423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a77f1b2e054'
down_revision = '586402ca7cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('countryName', sa.Text(), nullable=True),
    sa.Column('provinceName', sa.Text(), nullable=True),
    sa.Column('cityName', sa.Text(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('confirmedCount', sa.Integer(), nullable=True),
    sa.Column('suspectedCount', sa.Integer(), nullable=True),
    sa.Column('curedCount', sa.Integer(), nullable=True),
    sa.Column('deadCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_caches_updateTime'), 'day_caches', ['updateTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_caches_updateTime'), table_name='day_caches')
    op.drop_table('day_caches')
    # ### end Alembic commands ###
