"""empty message

Revision ID: 14548a7b78d0
Revises: 
Create Date: 2020-01-29 16:35:16.458208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14548a7b78d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('countryName', sa.Text(), nullable=True),
    sa.Column('provinceName', sa.Text(), nullable=True),
    sa.Column('cityName', sa.Text(), nullable=True),
    sa.Column('areaType', sa.Text(), nullable=True),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('confirmedCount', sa.Integer(), nullable=True),
    sa.Column('suspectedCount', sa.Integer(), nullable=True),
    sa.Column('curedCount', sa.Integer(), nullable=True),
    sa.Column('deadCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistic_data')
    # ### end Alembic commands ###
