"""empty message

Revision ID: 4f629080d342
Revises: 31da0ed98eba
Create Date: 2020-01-29 18:38:16.614784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f629080d342'
down_revision = '31da0ed98eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_time',
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('updateTime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('latest_time')
    # ### end Alembic commands ###
