"""empty message

Revision ID: 586402ca7cbc
Revises: 6eea1bd7e4d2
Create Date: 2020-01-31 19:07:09.399919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586402ca7cbc'
down_revision = '6eea1bd7e4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_logs_updateTime'), 'data_logs', ['updateTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_logs_updateTime'), table_name='data_logs')
    # ### end Alembic commands ###
