"""empty message

Revision ID: 63989d2d500f
Revises: dfceff7bfcb5
Create Date: 2020-02-03 18:07:12.106913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63989d2d500f'
down_revision = 'dfceff7bfcb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_log', sa.Column('logTime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_api_log_logTime'), 'api_log', ['logTime'], unique=False)
    op.drop_index('ix_api_log_updateTime', table_name='api_log')
    op.drop_column('api_log', 'updateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_log', sa.Column('updateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_api_log_updateTime', 'api_log', ['updateTime'], unique=False)
    op.drop_index(op.f('ix_api_log_logTime'), table_name='api_log')
    op.drop_column('api_log', 'logTime')
    # ### end Alembic commands ###
