"""empty message

Revision ID: 6eea1bd7e4d2
Revises: a35f5aa0efef
Create Date: 2020-01-31 15:02:34.342002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eea1bd7e4d2'
down_revision = 'a35f5aa0efef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('level', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'level')
    # ### end Alembic commands ###
