"""empty message

Revision ID: dfceff7bfcb5
Revises: 0a77f1b2e054
Create Date: 2020-02-03 18:00:20.171476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfceff7bfcb5'
down_revision = '0a77f1b2e054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('remoteAddr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_log_updateTime'), 'api_log', ['updateTime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_log_updateTime'), table_name='api_log')
    op.drop_table('api_log')
    # ### end Alembic commands ###
